# Root config — loaded by all child units via find_in_parent_folders("root.hcl")
#
# Directory hierarchy: <account>/<region>/<environment>/<module>/terragrunt.hcl
# Three config layers:
#   account.hcl  → AWS account id, profile, state bucket/table
#   region.hcl   → AWS region
#   env.hcl      → environment name, project name

locals {
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  env_vars     = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  account_name = local.account_vars.locals.account_name
  account_id   = local.account_vars.locals.account_id
  aws_profile  = try(local.account_vars.locals.aws_profile, "default")

  state_bucket = local.account_vars.locals.state_bucket
  state_lock_table = try(
    local.account_vars.locals.state_lock_table,
    "${local.account_vars.locals.project_prefix}-terraform-state-lock"
  )

  region = local.region_vars.locals.region

  env     = local.env_vars.locals.environment
  project = local.env_vars.locals.project
}

# Remote state: S3 + DynamoDB (created once via the tfstate module).
remote_state {
  backend = "s3"

  disable_dependency_optimization = true

  config = {
    bucket         = local.state_bucket
    key            = "${local.region}/${local.env}/${path_relative_to_include()}/terraform.tfstate"
    region         = local.region
    encrypt        = true
    dynamodb_table = local.state_lock_table
    profile        = local.aws_profile
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

terraform {
  extra_arguments "init_reconfigure" {
    commands  = ["init"]
    arguments = ["-reconfigure"]
  }

  extra_arguments "aws_profile" {
    commands = [
      "apply",
      "console",
      "destroy",
      "import",
      "init",
      "output",
      "plan",
      "providers",
      "refresh",
      "show",
      "state",
      "validate",
      "version",
    ]
    env_vars = {
      AWS_PROFILE        = local.aws_profile
      AWS_DEFAULT_REGION = local.region
      AWS_REGION         = local.region
    }
  }
}

# Provider version constraints stay in each module's versions.tf.
generate "provider" {
  path      = "provider_tg.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOT
    # Generated by Terragrunt — do not edit manually.
    provider "aws" {
      region  = "${local.region}"
      profile = "${local.aws_profile}"

      default_tags {
        tags = {
          Project     = "${local.project}"
          Environment = "${local.env}"
          Account     = "${local.account_name}"
          Region      = "${local.region}"
          ManagedBy   = "terraform"
        }
      }
    }
  EOT
}

inputs = {
  project     = local.project
  environment = local.env
  region      = local.region
  tags = {
    Project     = local.project
    Environment = local.env
    Account     = local.account_name
    AccountId   = local.account_id
    Region      = local.region
    ManagedBy   = "terraform"
  }
}
