resource "local_file" "ssh_config" {
  count = length(local.instances_output) > 0 ? 1 : 0

  filename = local.ssh_config_file_path
  content  = <<-EOT
# SSH Config for ${var.project}-${var.environment}
# Generated by Terraform - DO NOT EDIT MANUALLY
# Last updated: ${timestamp()}

# Define EC2 Instance
${join("\n", [for k, v in local.instances_output : "Host ${var.name_prefix}-${var.environment}\n    HostName ${local.dns_enabled && contains(keys(local.instance_dns_names), k) ? local.instance_dns_names[k] : v.public_ip}\n    User ubuntu\n    Port 22\n    IdentityFile ~/.ssh/${var.name_prefix}-${var.environment}"])}

# Access Public Subnet Instances (via EC2 Instance) - ubuntu
${join("\n", [for cidr in try(data.terraform_remote_state.vpc.outputs.public_subnet_cidrs, []) : "Host ${replace(cidr, "/^(\\d+\\.\\d+\\.\\d+)\\..*$/", "$1.*")}\n    User ubuntu\n    ProxyJump ${var.name_prefix}-${var.environment}\n    IdentityFile ~/.ssh/${var.name_prefix}-${var.environment}"])}

# Access Private Subnet Instances (via EC2 Instance) - ec2-user
${join("\n", [for cidr in try(data.terraform_remote_state.vpc.outputs.private_subnet_cidrs, []) : "Host ${replace(cidr, "/^(\\d+\\.\\d+\\.\\d+)\\..*$/", "$1.*")}\n    User ec2-user\n    ProxyJump ${var.name_prefix}-${var.environment}\n    IdentityFile ~/.ssh/${var.name_prefix}-${var.environment}"])}
EOT

  file_permission = "0644"
}

output "ssh_config_file_path" {
  description = "Path to the generated SSH config file"
  value       = length(local.instances_output) > 0 ? local.ssh_config_file_path : null
}

output "ssh_config_file_content" {
  description = "Content of the generated SSH config file"
  value       = length(local.instances_output) > 0 ? local_file.ssh_config[0].content : null
  sensitive   = false
}

