terraform {
  required_version = ">= 1.14"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.28"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "aws" {
  region = var.region
}

# VPC module must be deployed first
data "terraform_remote_state" "vpc" {
  backend   = "s3"
  workspace = terraform.workspace

  config = {
    bucket               = var.vpc_remote_state_bucket
    key                  = var.vpc_remote_state_key
    region               = var.region
    workspace_key_prefix = "env:development"
  }
}

module "ec2" {
  source = "../../"

  project     = var.project
  environment = var.environment
  region      = var.region

  vpc_remote_state_bucket               = var.vpc_remote_state_bucket
  vpc_remote_state_key                  = var.vpc_remote_state_key
  vpc_remote_state_workspace_key_prefix = "env:development"

  instance_count = var.instance_count

  # SSH key configuration
  key_path = var.key_path

  # Subnet configuration: GitLab should be in private subnet for security
  subnet_type = "private"

  instance_defaults = {
    instance_type                 = var.instance_type
    enable_monitoring             = var.enable_monitoring
    ebs_volume_size               = var.ebs_volume_size
    ebs_volume_type               = var.ebs_volume_type
    ebs_encrypted                 = var.ebs_encrypted
    enable_termination_protection = var.enable_termination_protection
  }

  # GitLab configuration
  gitlab_enabled = true

  # GitLab URLs and ports
  gitlab_external_url = var.gitlab_external_url
  gitlab_http_port    = var.gitlab_http_port
  gitlab_https_port   = var.gitlab_https_port
  gitlab_ssh_port     = var.gitlab_ssh_port

  # IAM permissions
  iam_instance_profile_enabled = var.iam_instance_profile_enabled
  enable_ecr                   = var.enable_ecr

  # SSM Session Manager
  enable_ssm_session_manager = var.enable_ssm_session_manager

  # Elastic IP for stable public IP
  enable_eip = var.enable_eip

  # Application Load Balancer (enabled by default for HTTPS and security)
  enable_alb          = var.enable_alb
  alb_port            = var.alb_port
  alb_protocol        = var.alb_protocol
  alb_target_port     = var.alb_target_port
  alb_certificate_arn = var.alb_certificate_arn

  # DNS configuration
  domain      = var.domain
  dns_enabled = var.dns_enabled
  dns_ttl     = var.dns_ttl

  tags = var.tags
}

# Generate SSH config for GitLab access via jump server
resource "local_file" "gitlab_ssh_config" {
  count = var.jump_server_host != null && length(module.ec2.instances) > 0 ? 1 : 0

  filename = pathexpand("~/.ssh/conf.d/gitlab-${var.environment}.conf")
  content = join("\n", [
    "# SSH Config for GitLab (${var.project}-${var.environment})",
    "# Generated by Terraform - DO NOT EDIT MANUALLY",
    "# Last updated: ${timestamp()}",
    "# Access GitLab via jump server: ${var.jump_server_host}",
    "",
    "# Jump Server (Proxy)",
    "Host jump-${var.environment}",
    "    HostName ${var.jump_server_host}",
    "    User ${var.jump_server_user}",
    "    Port ${var.jump_server_port}",
    "    IdentityFile ${var.jump_server_identity_file}",
    "    ForwardAgent yes",
    "    ServerAliveInterval 60",
    "    ServerAliveCountMax 3",
    "",
    "# GitLab Instance(s) via Jump Server",
    join("\n", [
      for k, v in module.ec2.instances : join("\n", [
        "Host gitlab-${var.environment}${var.instance_count > 1 ? "-${replace(k, "${var.project}-${var.environment}-", "")}" : ""}",
        "    HostName ${try(module.ec2.dns_names[k], v.private_ip)}",
        "    User git",
        "    Port ${var.gitlab_ssh_port}",
        "    ProxyJump jump-${var.environment}",
        "    IdentityFile ${var.jump_server_identity_file}",
        "    ForwardAgent yes",
        "    ServerAliveInterval 60",
        "    ServerAliveCountMax 3",
        "    # GitLab SSH configuration",
        "    PreferredAuthentications publickey",
        "    IdentitiesOnly yes",
      ])
    ]),
    "",
    "# GitLab via Private IP (alternative access method)",
    join("\n", [
      for k, v in module.ec2.instances : join("\n", [
        "Host gitlab-${var.environment}${var.instance_count > 1 ? "-${replace(k, "${var.project}-${var.environment}-", "")}" : ""}-ip",
        "    HostName ${v.private_ip}",
        "    User git",
        "    Port ${var.gitlab_ssh_port}",
        "    ProxyJump jump-${var.environment}",
        "    IdentityFile ${var.jump_server_identity_file}",
        "    ForwardAgent yes",
        "    ServerAliveInterval 60",
        "    ServerAliveCountMax 3",
      ])
    ]),
  ])

  file_permission = "0644"
}
